Allow CORS
DEFRA/epr-calculator-api pull request #142
Opened 2024-12-18 09:55 UTC by davidjayakumarEviden

482149 Results file download - Integrate GET results file Endpoint

2024-12-18 13:19 UTC, johnbenjamin-defra requested changes

2024-12-18 13:19 UTC, johnbenjamin-defra commented on src/EPR.Calculator.API/appsettings.Development.json
> +    "BlobStorage": {
Can you correct the alignment or revert the changes if not required?

2024-12-18 13:30 UTC, tim-powell-eviden approved these changes

2024-12-18 14:08 UTC, davidjayakumarEviden commented on src/EPR.Calculator.API/appsettings.Development.json
Reverted the change

2024-12-19 15:11 UTC, tim-powell-eviden approved these changes

2024-12-19 15:13 UTC, johnbenjamin-defra approved these changes

2024-12-23 10:14 UTC, merged